import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
import { ChevronDown, ChevronUp, CheckCircle2, BookOpen, Zap, Layers, Check, Copy } from 'lucide-react';
export const UnitSyllabusAccordion = ({ units, onToggleUnitCompleted, onToggleTwoMark }) => {
    const [expandedUnit, setExpandedUnit] = useState(1);
    const [revealedAnswers, setRevealedAnswers] = useState({});
    const [copiedId, setCopiedId] = useState(null);
    const toggleAnswerReveal = (qId) => {
        setRevealedAnswers(prev => ({ ...prev, [qId]: !prev[qId] }));
    };
    const handleCopy = (text, id) => {
        navigator.clipboard.writeText(text);
        setCopiedId(id);
        setTimeout(() => setCopiedId(null), 2000);
    };
    return (_jsx("div", { className: "space-y-4", children: units.map((unit) => {
            const isExpanded = expandedUnit === unit.unitNumber;
            const confidenceBadge = {
                strong: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300 border-emerald-200 dark:border-emerald-900',
                moderate: 'bg-amber-100 text-amber-800 dark:bg-amber-950/60 dark:text-amber-300 border-amber-200 dark:border-amber-900',
                weak: 'bg-rose-100 text-rose-800 dark:bg-rose-950/60 dark:text-rose-300 border-rose-200 dark:border-rose-900',
                unprepared: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700'
            }[unit.confidenceLevel || 'unprepared'];
            return (_jsxs("div", { className: `rounded-2xl border transition-all duration-200 ${unit.isCompleted
                    ? 'bg-slate-50/80 dark:bg-slate-900/60 border-slate-200 dark:border-slate-800'
                    : isExpanded
                        ? 'bg-white dark:bg-slate-900 border-indigo-300 dark:border-indigo-800 shadow-md'
                        : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 shadow-xs'}`, children: [_jsxs("div", { onClick: () => setExpandedUnit(isExpanded ? 0 : unit.unitNumber), className: "p-5 flex items-center justify-between gap-4 cursor-pointer select-none", children: [_jsxs("div", { className: "flex items-center gap-3.5", children: [_jsx("button", { type: "button", onClick: (e) => {
                                            e.stopPropagation();
                                            onToggleUnitCompleted(unit.unitNumber, unit.isCompleted);
                                        }, className: `w-6 h-6 rounded-lg flex items-center justify-center transition shrink-0 ${unit.isCompleted
                                            ? 'bg-emerald-600 text-white shadow-xs'
                                            : 'border-2 border-slate-300 dark:border-slate-700 hover:border-indigo-600'}`, title: "Mark unit completed", children: unit.isCompleted && _jsx(CheckCircle2, { className: "w-4 h-4" }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsxs("span", { className: "px-2 py-0.5 rounded text-[10px] font-extrabold bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 uppercase", children: ["Unit ", unit.unitNumber] }), _jsx("h3", { className: `text-sm font-extrabold ${unit.isCompleted ? 'line-through text-slate-500' : 'text-slate-900 dark:text-white'}`, children: unit.unitTitle })] }), _jsxs("p", { className: "text-xs text-slate-500 mt-0.5", children: ["Weightage: ~", unit.weightageMarks, " Marks \u2022 ", unit.topics.length, " Core Topics \u2022 ", unit.twoMarks?.length || 0, " Part-A 2-Marks"] })] })] }), _jsxs("div", { className: "flex items-center gap-2 shrink-0", children: [_jsx("span", { className: `px-2.5 py-0.5 rounded-full text-[11px] font-bold border capitalize hidden sm:inline-block ${confidenceBadge}`, children: unit.confidenceLevel || 'unprepared' }), _jsx("div", { className: "p-1.5 rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-white", children: isExpanded ? _jsx(ChevronUp, { className: "w-5 h-5" }) : _jsx(ChevronDown, { className: "w-5 h-5" }) })] })] }), isExpanded && (_jsxs("div", { className: "px-5 pb-6 pt-2 border-t border-slate-100 dark:border-slate-800 space-y-6", children: [_jsxs("div", { className: "space-y-2", children: [_jsxs("span", { className: "text-xs font-extrabold text-slate-800 dark:text-slate-200 flex items-center gap-1.5", children: [_jsx(Layers, { className: "w-3.5 h-3.5 text-indigo-600" }), " Prescribed University Syllabus Topics:"] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-2", children: unit.topics.map((topic, tIdx) => (_jsxs("div", { className: "p-2.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200/80 dark:border-slate-800 text-xs text-slate-700 dark:text-slate-300 flex items-start gap-2", children: [_jsx("span", { className: "text-indigo-600 dark:text-indigo-400 font-bold", children: "\u2022" }), _jsx("span", { children: topic })] }, tIdx))) })] }), unit.twoMarks && unit.twoMarks.length > 0 && (_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "text-xs font-extrabold text-indigo-900 dark:text-indigo-300 flex items-center gap-1.5", children: [_jsx(Zap, { className: "w-4 h-4 text-amber-500" }), " Part A: High-Frequency 2-Mark Definitions"] }), _jsxs("span", { className: "text-[11px] text-slate-400", children: [unit.twoMarks.filter(q => q.isMastered).length, "/", unit.twoMarks.length, " Mastered"] })] }), _jsx("div", { className: "space-y-3", children: unit.twoMarks.map((q) => {
                                            const isRevealed = revealedAnswers[q.id];
                                            const isCopied = copiedId === q.id;
                                            return (_jsxs("div", { className: "p-4 rounded-xl border border-indigo-100 dark:border-indigo-950 bg-indigo-50/40 dark:bg-indigo-950/20 space-y-2.5", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { className: "flex items-start gap-2.5", children: [_jsx("button", { type: "button", onClick: () => onToggleTwoMark(q.id), className: `w-5 h-5 rounded-md flex items-center justify-center transition shrink-0 mt-0.5 ${q.isMastered
                                                                            ? 'bg-emerald-600 text-white'
                                                                            : 'border border-slate-300 dark:border-slate-700 hover:border-emerald-500'}`, title: "Mark 2-mark mastered", children: q.isMastered && _jsx(Check, { className: "w-3.5 h-3.5" }) }), _jsx("div", { children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "text-xs font-bold text-slate-900 dark:text-white", children: ["Q: ", q.question] }), q.frequency.includes('High') && (_jsx("span", { className: "px-2 py-0.5 rounded text-[10px] font-bold bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300 shrink-0", children: "\uD83D\uDD25 Repeated 4+ Times" }))] }) })] }), _jsx("button", { type: "button", onClick: () => toggleAnswerReveal(q.id), className: "text-xs font-bold text-indigo-600 dark:text-indigo-400 hover:underline shrink-0", children: isRevealed ? 'Hide Answer' : 'Show Answer' })] }), isRevealed && (_jsxs("div", { className: "p-3 rounded-lg bg-white dark:bg-slate-900 border border-indigo-200 dark:border-indigo-800 space-y-2 animate-fade-in", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-[11px] font-bold text-slate-500", children: "Concise Board Exam Answer:" }), _jsxs("button", { type: "button", onClick: () => handleCopy(q.conciseAnswer, q.id), className: "text-[10px] font-bold text-slate-500 hover:text-slate-800 dark:hover:text-white flex items-center gap-1", children: [isCopied ? _jsx(Check, { className: "w-3 h-3 text-emerald-600" }) : _jsx(Copy, { className: "w-3 h-3" }), isCopied ? 'Copied' : 'Copy'] })] }), _jsx("p", { className: "text-xs text-slate-800 dark:text-slate-200 font-sans leading-relaxed whitespace-pre-line", children: q.conciseAnswer }), q.keyKeywords && q.keyKeywords.length > 0 && (_jsxs("div", { className: "flex flex-wrap items-center gap-1.5 pt-1", children: [_jsx("span", { className: "text-[10px] font-bold text-indigo-600 dark:text-indigo-400", children: "Key Evaluator Phrases:" }), q.keyKeywords.map((kw, kIdx) => (_jsx("span", { className: "px-2 py-0.5 rounded bg-amber-50 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 text-[10px] font-mono border border-amber-200/50", children: kw }, kIdx)))] }))] }))] }, q.id));
                                        }) })] })), unit.bigQuestions && unit.bigQuestions.length > 0 && (_jsxs("div", { className: "space-y-3", children: [_jsxs("span", { className: "text-xs font-extrabold text-purple-900 dark:text-purple-300 flex items-center gap-1.5", children: [_jsx(BookOpen, { className: "w-4 h-4 text-purple-600" }), " Part B: Recurring 13 / 16-Mark Question Blueprints"] }), _jsx("div", { className: "space-y-3", children: unit.bigQuestions.map((bq) => (_jsxs("div", { className: "p-4 rounded-xl border border-purple-100 dark:border-purple-950 bg-purple-50/30 dark:bg-purple-950/10 space-y-3", children: [_jsx("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-2", children: _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "px-2 py-0.5 rounded text-[10px] font-extrabold bg-purple-600 text-white", children: [bq.marks, " Marks"] }), _jsx("h4", { className: "text-xs font-extrabold text-slate-900 dark:text-white", children: bq.title })] }), _jsxs("span", { className: "text-[10px] text-slate-500 block mt-0.5", children: ["Appeared in University Exams: ", bq.previousExamYears.join(', ')] })] }) }), _jsxs("div", { className: "p-3.5 rounded-xl bg-white dark:bg-slate-900 border border-purple-200/60 dark:border-purple-900/50 space-y-2 text-xs", children: [_jsx("span", { className: "font-bold text-purple-700 dark:text-purple-300 block text-[11px]", children: "\uD83D\uDCCB Step-by-Step Scoring Blueprint for 100% Marks:" }), _jsx("div", { className: "space-y-2 pl-2", children: bq.stepByStepBlueprint.map((step, sIdx) => (_jsxs("div", { className: "space-y-0.5", children: [_jsx("p", { className: "font-bold text-slate-800 dark:text-slate-200", children: step.heading }), _jsx("p", { className: "text-slate-600 dark:text-slate-400 text-[11px]", children: step.content }), step.diagramHint && (_jsxs("div", { className: "p-1.5 rounded bg-amber-50 dark:bg-amber-950/40 border border-amber-200/40 text-[10px] text-amber-800 dark:text-amber-300 font-mono", children: ["\uD83D\uDDBC\uFE0F Diagram: ", step.diagramHint] }))] }, sIdx))) })] })] }, bq.id))) })] }))] }))] }, unit.unitNumber));
        }) }));
};
