import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { BarChart2, TrendingUp, Sparkles, Search, Flame, AlertCircle, Play } from 'lucide-react';
import { PYQ_TOPIC_FREQUENCIES } from '../data/featureHubData';
export const PyqTrendAnalyzerPage = () => {
    const [selectedSubject, setSelectedSubject] = useState('all');
    const [selectedYieldTier, setSelectedYieldTier] = useState('all');
    const [searchQuery, setSearchQuery] = useState('');
    const subjects = Array.from(new Set(PYQ_TOPIC_FREQUENCIES.map(p => p.subject)));
    const filteredTopics = PYQ_TOPIC_FREQUENCIES.filter(item => {
        if (selectedSubject !== 'all' && item.subject !== selectedSubject)
            return false;
        if (selectedYieldTier !== 'all' && item.yieldTier !== selectedYieldTier)
            return false;
        if (searchQuery.trim()) {
            const q = searchQuery.toLowerCase();
            return (item.topicName.toLowerCase().includes(q) ||
                item.subject.toLowerCase().includes(q) ||
                item.chapter.toLowerCase().includes(q) ||
                item.typicalQuestionArchetype.toLowerCase().includes(q));
        }
        return true;
    });
    const highYieldCount = PYQ_TOPIC_FREQUENCIES.filter(p => p.yieldTier.includes('High-Yield')).length;
    const mediumYieldCount = PYQ_TOPIC_FREQUENCIES.filter(p => p.yieldTier.includes('Medium-Yield')).length;
    const lowYieldCount = PYQ_TOPIC_FREQUENCIES.filter(p => p.yieldTier.includes('Low-Yield')).length;
    return (_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8", children: [_jsx("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-slate-200 dark:border-slate-800", children: _jsxs("div", { children: [_jsxs("div", { className: "inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-700 dark:bg-slate-800 dark:text-blue-300 text-xs font-semibold mb-2", children: [_jsx(BarChart2, { className: "w-3.5 h-3.5" }), "5-Year Pattern Intelligence & Weightage Heatmap"] }), _jsx("h1", { className: "text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white", children: "PYQ Trend Analyzer & Yield Matrix" }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400 mt-1 max-w-2xl", children: "Focus your revision on what actually repeats. Analyze question frequency from 2021 to 2025 across official competitive exam shifts." })] }) }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-4", children: [_jsxs("div", { onClick: () => setSelectedYieldTier(selectedYieldTier === 'High-Yield (Must Do)' ? 'all' : 'High-Yield (Must Do)'), className: `p-4 rounded-xl border cursor-pointer transition shadow-sm ${selectedYieldTier === 'High-Yield (Must Do)'
                            ? 'bg-rose-50 border-rose-400 dark:bg-rose-950/40 dark:border-rose-700 ring-2 ring-rose-500'
                            : 'bg-white border-slate-200 dark:bg-slate-900 dark:border-slate-800 hover:border-rose-300'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "text-xs font-bold text-rose-600 dark:text-rose-400 flex items-center gap-1.5", children: [_jsx(Flame, { className: "w-4 h-4 fill-rose-500 text-rose-500" }), " Tier 1: High Yield (Must-Do)"] }), _jsxs("span", { className: "text-xs font-mono font-bold text-slate-400", children: [highYieldCount, " Topics"] })] }), _jsx("p", { className: "text-xs text-slate-600 dark:text-slate-400 mt-2", children: "4-8 questions per paper. Contributes ~60% of total score with predictable repeat formulas." })] }), _jsxs("div", { onClick: () => setSelectedYieldTier(selectedYieldTier === 'Medium-Yield' ? 'all' : 'Medium-Yield'), className: `p-4 rounded-xl border cursor-pointer transition shadow-sm ${selectedYieldTier === 'Medium-Yield'
                            ? 'bg-blue-50 border-blue-400 dark:bg-blue-950/40 dark:border-blue-700 ring-2 ring-blue-500'
                            : 'bg-white border-slate-200 dark:bg-slate-900 dark:border-slate-800 hover:border-blue-300'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "text-xs font-bold text-blue-600 dark:text-blue-400 flex items-center gap-1.5", children: [_jsx(TrendingUp, { className: "w-4 h-4 text-blue-600" }), " Tier 2: Medium Yield"] }), _jsxs("span", { className: "text-xs font-mono font-bold text-slate-400", children: [mediumYieldCount, " Topics"] })] }), _jsx("p", { className: "text-xs text-slate-600 dark:text-slate-400 mt-2", children: "2-3 questions per paper. Steady recurring patterns that secure benchmark passing scores." })] }), _jsxs("div", { onClick: () => setSelectedYieldTier(selectedYieldTier === 'Low-Yield (Optional)' ? 'all' : 'Low-Yield (Optional)'), className: `p-4 rounded-xl border cursor-pointer transition shadow-sm ${selectedYieldTier === 'Low-Yield (Optional)'
                            ? 'bg-slate-100 border-slate-400 dark:bg-slate-800 dark:border-slate-600 ring-2 ring-slate-500'
                            : 'bg-white border-slate-200 dark:bg-slate-900 dark:border-slate-800 hover:border-slate-300'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "text-xs font-bold text-slate-600 dark:text-slate-400 flex items-center gap-1.5", children: [_jsx(AlertCircle, { className: "w-4 h-4 text-slate-400" }), " Tier 3: Low Yield"] }), _jsxs("span", { className: "text-xs font-mono font-bold text-slate-400", children: [lowYieldCount, " Topics"] })] }), _jsx("p", { className: "text-xs text-slate-600 dark:text-slate-400 mt-2", children: "0-1 questions occasionally. Heavy theory with low return per hour of revision time." })] })] }), _jsx("div", { className: "p-4 rounded-xl bg-white border border-slate-200 dark:bg-slate-900 dark:border-slate-800 shadow-sm space-y-3", children: _jsxs("div", { className: "flex flex-col lg:flex-row items-center justify-between gap-4", children: [_jsxs("div", { className: "relative w-full lg:w-96", children: [_jsx(Search, { className: "w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" }), _jsx("input", { type: "text", placeholder: "Search topic, chapter, or question archetype...", value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), className: "w-full pl-9 pr-4 py-2 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-slate-800 dark:border-slate-700 dark:text-white" })] }), _jsx("div", { className: "flex flex-wrap items-center gap-3 w-full lg:w-auto text-xs", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-slate-400", children: "Subject:" }), _jsxs("select", { value: selectedSubject, onChange: (e) => setSelectedSubject(e.target.value), className: "px-3 py-2 rounded-lg bg-slate-50 border border-slate-200 font-semibold dark:bg-slate-800 dark:border-slate-700 dark:text-white", children: [_jsx("option", { value: "all", children: "All Subjects" }), subjects.map(s => _jsx("option", { value: s, children: s }, s))] })] }) })] }) }), _jsx("div", { className: "space-y-4", children: filteredTopics.map((topic) => {
                    const maxFreq = Math.max(...topic.fiveYearTrend.map(y => y.questionCount), 1);
                    const isHighYield = topic.yieldTier.includes('High-Yield');
                    const isMediumYield = topic.yieldTier.includes('Medium-Yield');
                    return (_jsxs("div", { className: "p-6 rounded-2xl bg-white border border-slate-200 dark:bg-slate-900 dark:border-slate-800 shadow-sm space-y-4 hover:border-blue-300 transition", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100 dark:border-slate-800", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: `px-2.5 py-0.5 rounded-full text-xs font-bold ${isHighYield
                                                    ? 'bg-rose-50 text-rose-700 border border-rose-200 dark:bg-rose-950/50 dark:text-rose-300 dark:border-rose-800'
                                                    : isMediumYield
                                                        ? 'bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-950/50 dark:text-blue-300 dark:border-blue-800'
                                                        : 'bg-slate-100 text-slate-700 border border-slate-200 dark:bg-slate-800 dark:text-slate-300'}`, children: topic.yieldTier.toUpperCase() }), _jsx("h3", { className: "text-base font-bold text-slate-900 dark:text-white", children: topic.topicName }), _jsxs("span", { className: "text-xs text-slate-400", children: ["(", topic.subject, " \u2022 ", topic.chapter, ")"] })] }), _jsxs("div", { className: "flex items-center gap-3 text-xs", children: [_jsxs("span", { className: "text-slate-500", children: ["Weightage: ", _jsxs("strong", { className: "text-blue-600 font-mono", children: ["~", topic.averageMarksWeightage, " marks"] })] }), _jsxs(Link, { to: `/practice?subject=${encodeURIComponent(topic.subject)}`, className: "px-3.5 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white font-bold transition flex items-center gap-1 shadow-xs", children: [_jsx(Play, { className: "w-3 h-3 fill-white" }), " Launch Topic Drill"] })] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6 pt-2", children: [_jsxs("div", { className: "p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-3", children: [_jsxs("span", { className: "text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center gap-1.5", children: [_jsx(BarChart2, { className: "w-3.5 h-3.5 text-blue-600" }), " 5-Year Shift Question Volume (2021 - 2025):"] }), _jsx("div", { className: "flex items-end justify-between gap-3 h-24 pt-4 px-2", children: topic.fiveYearTrend.map((y) => {
                                                    const heightPercent = Math.round((y.questionCount / maxFreq) * 100);
                                                    return (_jsxs("div", { className: "flex-1 flex flex-col items-center gap-1.5 h-full justify-end", children: [_jsx("span", { className: "text-[10px] font-mono font-bold text-slate-600 dark:text-slate-300", children: y.questionCount }), _jsx("div", { className: `w-full max-w-[28px] rounded-t-md transition-all ${isHighYield ? 'bg-rose-500' : 'bg-blue-600'}`, style: { height: `${Math.max(12, heightPercent)}%` } }), _jsx("span", { className: "text-[10px] text-slate-400 font-mono", children: y.year })] }, y.year));
                                                }) })] }), _jsxs("div", { className: "space-y-3 text-xs", children: [_jsxs("div", { children: [_jsx("span", { className: "font-bold text-slate-800 dark:text-slate-200", children: "Examiner Question Archetype:" }), _jsx("p", { className: "mt-1.5 text-slate-600 dark:text-slate-300 leading-relaxed bg-slate-50 dark:bg-slate-800/60 p-2.5 rounded-lg border border-slate-100 dark:border-slate-700", children: topic.typicalQuestionArchetype })] }), _jsxs("div", { className: "p-2.5 rounded-lg bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800 text-amber-900 dark:text-amber-200 space-y-0.5 text-[11px]", children: [_jsxs("span", { className: "font-bold flex items-center gap-1 text-amber-800 dark:text-amber-300", children: [_jsx(Sparkles, { className: "w-3 h-3 text-amber-500" }), " Historical PYQ Pool:"] }), _jsxs("p", { children: [topic.pyqCount, " solved previous-year questions logged in system."] })] })] })] })] }, topic.id));
                }) })] }));
};
export default PyqTrendAnalyzerPage;
